import fs from 'node:fs';
import path from 'node:path';
import { TelegramClient } from 'teleproto';
import { StringSession } from 'teleproto/sessions';
import * as mongo from './mongo.js';

const storeFile = path.resolve('data/mtproto.json');
let clientPromise = null;
let mongoLoaded = false;

function env(name, fallback = '') {
  return String(process.env[name] || fallback).trim();
}

function readStore() {
  try {
    const data = JSON.parse(fs.readFileSync(storeFile, 'utf8'));
    return data && typeof data === 'object' ? data : {};
  } catch {
    return {};
  }
}

function writeStore(data) {
  fs.mkdirSync(path.dirname(storeFile), { recursive: true });
  fs.writeFileSync(storeFile, JSON.stringify(data, null, 2), { mode: 0o600 });
  try { fs.chmodSync(storeFile, 0o600); } catch {}
}

export function getConfig() {
  const saved = readStore();
  return {
    apiId: Number(saved.apiId || env('TELEGRAM_API_ID', env('API_ID')) || 0),
    apiHash: String(saved.apiHash || env('TELEGRAM_API_HASH', env('API_HASH')) || '').trim(),
    session: String(saved.session || env('TELEGRAM_SESSION_STRING', env('USER_SESSION_STRING')) || '').trim(),
  };
}

export async function initialize() {
  if (mongoLoaded) return getConfig();
  mongoLoaded = true;

  const local = getConfig();
  if (local.apiId > 0 && local.apiHash && local.session) return local;

  try {
    const remote = await mongo.getMtprotoConfig();
    if (remote?.apiId && remote?.apiHash && remote?.session) {
      writeStore({
        apiId: Number(remote.apiId),
        apiHash: String(remote.apiHash),
        session: String(remote.session),
      });
      clientPromise = null;
      console.log('[mtproto] configuration restored from MongoDB');
    }
  } catch (err) {
    console.warn(`[mtproto] MongoDB restore skipped: ${err.message}`);
  }

  return getConfig();
}

export function isEnabled() {
  const c = getConfig();
  return Boolean(c.apiId > 0 && c.apiHash && c.session);
}

function pyrogramToTeleproto(session) {
  let raw = String(session || '').trim().replace(/-/g, '+').replace(/_/g, '/');
  while (raw.length % 4) raw += '=';
  const data = Buffer.from(raw, 'base64');
  // Pyrogram session string layout:
  // dc_id(1) + api_id(4) + test_mode(1) + auth_key(256) + user_id(8) + is_bot(1)
  if (data.length !== 271) return null;

  const dcId = data.readUInt8(0);
  if (dcId < 1 || dcId > 5) return null;

  const authKey = data.subarray(6, 262);
  if (authKey.length !== 256) return null;

  const dcAddresses = {
    1: '149.154.175.53',
    2: '149.154.167.51',
    3: '149.154.175.100',
    4: '149.154.167.91',
    5: '91.108.56.130',
  };
  const address = Buffer.from(dcAddresses[dcId]);
  const addressLen = Buffer.alloc(2);
  addressLen.writeInt16BE(address.length, 0);
  const port = Buffer.alloc(2);
  port.writeInt16BE(443, 0);

  return '1' + Buffer.concat([
    Buffer.from([dcId]),
    addressLen,
    address,
    port,
    authKey,
  ]).toString('base64');
}

function normalizeSession(session) {
  const value = String(session || '').trim();
  if (!value) throw new Error('MTProto session is empty');

  try {
    // Native teleproto StringSession.
    new StringSession(value);
    return value;
  } catch (err) {
    const converted = pyrogramToTeleproto(value);
    if (converted) {
      console.log('[mtproto] Pyrogram session detected; converting in memory to teleproto format');
      return converted;
    }
    throw new Error(
      'Invalid MTProto session string. Use a teleproto/GramJS-compatible session, or a Pyrogram session string generated by Pyrogram.',
    );
  }
}

export function saveConfig({ apiId, apiHash, session }) {
  const current = getConfig();
  const next = {
    apiId: Number(apiId || current.apiId || 0),
    apiHash: String(apiHash || current.apiHash || '').trim(),
    session: String(session || current.session || '').trim(),
  };
  if (!next.apiId || !next.apiHash || !next.session) {
    throw new Error('API ID, API Hash and Session String are all required');
  }
  writeStore(next);
  clientPromise = null;

  // Keep a local copy for immediate use and persist the same configuration
  // in MongoDB so Koyeb/Heroku redeploys can restore it.
  mongo.saveMtprotoConfig(next).catch((err) => {
    console.warn(`[mtproto] MongoDB persistence failed: ${err.message}`);
  });

  return { apiId: next.apiId, configured: true };
}

export function clearConfig() {
  writeStore({});
  clientPromise = null;
  mongo.clearMtprotoConfig().catch((err) => {
    console.warn(`[mtproto] MongoDB clear failed: ${err.message}`);
  });
}

export function status() {
  const c = getConfig();
  return {
    apiId: c.apiId,
    hasApiHash: Boolean(c.apiHash),
    hasSession: Boolean(c.session),
    enabled: Boolean(c.apiId > 0 && c.apiHash && c.session),
  };
}

async function getClient() {
  if (!isEnabled()) return null;
  if (clientPromise) return clientPromise;

  clientPromise = (async () => {
    const c = getConfig();

    const client = new TelegramClient(
      new StringSession(normalizeSession(c.session)),
      c.apiId,
      c.apiHash,
      {
        connectionRetries: 5,
        autoReconnect: true,
        floodSleepThreshold: 60,
      },
    );

    await client.connect();
    await client.getMe();
    console.log('[mtproto] large-file session connected');
    return client;
  })().catch((err) => {
    clientPromise = null;
    throw err;
  });

  return clientPromise;
}

export async function testConnection() {
  const client = await getClient();
  if (!client) throw new Error('MTProto is not configured');
  const me = await client.getMe();
  return {
    id: String(me?.id || ''),
    username: me?.username ? String(me.username) : '',
    premium: Boolean(me?.premium),
  };
}

export async function sendLargeFile({ chatId, filePath, caption, onProgress }) {
  const client = await getClient();
  if (!client) throw new Error('MTProto session is not configured');

  let target = chatId;
  try {
    target = await client.getEntity(chatId);
  } catch {
    try {
      const dialogs = await client.getDialogs({ limit: 1000 });
      const wanted = String(chatId);
      const match = dialogs.find((d) => String(d?.id || '') === wanted || String(d?.peer?.channelId || '') === wanted);
      if (match?.entity) target = match.entity;
      else throw new Error('MTProto account cannot resolve the target chat. Use a public @channelusername or make sure the account has joined/opened the dump channel.');
    } catch (resolveErr) {
      throw new Error(`cannot resolve MTProto target: ${resolveErr.message}`);
    }
  }

  const workers = Math.max(1, Math.min(Number(process.env.MT_PROTO_WORKERS || 16), 32));

  return client.sendFile(target, {
    file: filePath,
    caption,
    forceDocument: false,
    supportsStreaming: true,
    workers,
    progressCallback: (uploaded, total) => {
      try {
        onProgress?.(Number(uploaded) || 0, Number(total) || 0);
      } catch {}
    },
  });
}
